blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "DRAFT"
        PUBLISHED = "PB", "Published"
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)

    objects = models.Manager()
    published = PublishedManager()

    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]
    
    
    def __str__(self):
        return f'Коментарий оставил {self.name} для {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label='Имя')
    email = forms.EmailField(label='От кого')
    to = forms.EmailField(label='Кому')
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea,
        label='Комментарий'
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField(label='Запросы')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from django.http import Http404
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 4)
    page_number = request.GET.get('posts', 1)
    posts = paginator.page(page_number)
    return render(request, "blog/post/list.html", {"posts": posts, 'tag': tag})

def post_detail(request, year, month, day, post):
    try:
        post = Post.published.get(
                                    slug=post,
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day
                                )
        comments = post.comments.filter(active=True)
        form = CommentForm()

        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    except Post.DoesNotExist:
        raise Http404("No Post found")
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, "form": form, 'similar_posts': similar_posts})

def post_share(request, post_id):
    try:
        post = Post.published.get(id=post_id)
        sent = False
        if request.method == 'POST':
            form = EmailPostForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                post_url = request.build_absolute_uri(post.get_absolute_url())
                subject = f"{cd['name']} рекомендует вам прочесть {post.title}"
                message = f"Посмотреть {post.title} по адресу {post_url}\n\nСообщение от {cd['name']}: {cd['comments']}"
                send_mail(subject, message, 'rty.sem@yandex.ru', [cd['to']])
                sent = True
        else:
            form = EmailPostForm()
    except Post.DoesNotExist:
        raise Http404("No Post Found")
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

@require_POST
def post_comment(request, post_id):
    try:
        post = Post.published.get(id=post_id)
        comment = None
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
    except Post.DoesNotExist:
        raise Http404("No Post Found")
    return render(request, 'blog/post/comments.html', {'post': post, 'form': form, 'comment': comment})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = (Post.published.annotate(search=SearchVector('title', 'body')).filter(search=query))
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})
        

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/styles.css" %}" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
              <a href="{% url "blog:post_list" %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <svg class="bi me-2" width="40" height="32" aria-hidden="true"><use xlink:href="#bootstrap"></use></svg>
                <span class="fs-4">My Blog</span>
              </a>
              <a href="{% url "blog:post_search" %}" class="btn btn-danger">Поиск</a>
            </header>
            <h5>Мной было написанно {% total_posts %} постов</h5>
            {% show_latest_posts %}
          </div>
        {% block body %}{% endblock %}
        <div class="container">
          <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
              <a href="/blog" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1" aria-label="My Blog"></a>
              <span class="mb-3 mb-md-0 text-body-secondary">© 2025 Simon Babushkin</span>
            </div>
          </footer>
        </div>
    </body>
</html>

blog/templates/blog/post/comments.html
{% load crispy_forms_tags %}
{% if comment %}
    <h1>Коментарий успешно добавлен</h1>
    <a href="{{ post.get_absolute_url }}">Вернуться к посту</a>
{% else %}
    <h4>Добавить коментарий</h4>
    <form action="{% url "blog:post_comment" post.id %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button class="btn btn-success" type="submit">Добавить</button>
    </form>
{% endif %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}
{% block body %}
    <div class="container-sm">
        <h1>{{ post.title }}</h1>
        <br>
        <div class="form-control border-black">
            <pre>{{ post.body }}</pre>
        </div>
        <br>
        <h5><p>{{ post.publish }} {{ post.author }}</p></h5>
        <br><br><br><br><br><br><br> 
        <br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br>
        <div class="alert alert-info" role="alert">
            <h5>Схожие посты</h5>
            {% for post in similar_posts %}
                <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
            {% empty %}
                Нет схожих постов
            {% endfor %}
        </div>
        <p><a href="{% url "blog:post_share" post.id %}" class="link-underline-secondary">Отправить по почте</a></p>
        <h4>{{ comments.count }} comment{{ comments.count|pluralize }}</h4>
        {% for comment in comments %}
            <div class="alert alert-dark" role="alert">
                <p>
                    <h5>Коментарий {{ forloop.counter }} от {{ comment.name }}</h5>
                    {{ comment.created }}
                </p>
                {{ comment.body }}
            </div>
        {% empty %}
            <p>Нет коментариев</p>
        {% endfor %}
        <br><br><br><br>
        {% include "blog/post/comments.html" %}
    </div>

{% endblock %}

blog/templates/blog/post/latest_posts.html
<div class="alert alert-success" role="alert">
    <h5>Последние посты</h5>
    <ul>
        {% for post in latest_posts %}
            <li><a href="{{ post.get_absolute_url }}" >{{ post.title }}</a></li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}

{% block body %}
    <div class="container-md">
        <h1>Посты</h1>
        <div class="list-group">
            {% if tag %}
                <h3>Посты с тегом "{{ tag.name }}"</h3>
            {% endif %}
            {% for post in posts %}
                <a href="{{ post.get_absolute_url }}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{post.title}}</h5>
                        <small class="text-body-secondary">{{post.publish}}</small>
                    </div>
                    <p class="mb-1">{{post.body|truncatewords:30}}</p>
                </a>
                <p class ="mb-1">
                    {% for tag in post.tags.all %}
                        <a class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" href="{% url "blog:post_list_by_tag" tag.slug %}">{{tag.name}}</a>
                        {% if not foorloop.last %}, {% endif %}
                    {% endfor %}
                </p>
            {% endfor %}
        </div>
        <br><br>
        <nav aria-label="Page navigation example">
            <ul class="pagination">
              {% if posts.has_previous %}
                    <li class="page-item"><a class="page-link" href="?posts={{ posts.previous_page_number }}">Назад</a></li>
              {% endif %}
              {%for num in posts.paginator.page_range%}
                    <li class="page-item"><a class="page-link" href="?posts={{ num }}">{{ num }}</a></li>
              {% endfor %}
              {% if posts.has_next %}
                    <li class="page-item"><a class="page-link" href="?posts={{ posts.next_page_number }}">Вперед</a></li>
              {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load crispy_forms_tags %}

{% block title %} Поиск {% endblock %}

{% block body %}
    <div class="container">
        {% if query %}
        <h3>Посты содержащие "{{ query }}"</h1>
        <h5>Найдено {{ results.count }}</h5>
        {% for post in results %}
            <h5><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
            {{ post.body|truncatewords:30 }}
            {% empty %}
                <p>По вашему запросу не ничего не найдено</p>
        {% endfor %}
        <a class="btn btn-success" href="{% url "blog:post_search" %}">Повторить поиск</a>
        {% else %}
            <h1>Поиск постов</h1>
            <form method="get">
                {{form|crispy}}
                <br><br>
                <input class="btn btn-primary" type="submit" value="Найти">
            </form>
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Отпраивить по почте{% endblock %}
{% block body %}
    <div class="container-md">
        {% if sent %}
            <h1>E-mail отправлен успешно</h1>
            <p>"{{ post.title }}": успешно отправлен {{ form.cleaned_data.to }}</p>
        {% else %}
            <h1>Отправить "{{ post.title }}" по e-mail</h1>
            <div class="user_container">
                {% load crispy_forms_tags %}
                <form method="post">
                    <style>
                        .user_container
                        {
                            width: 35%;   
                        }
                    </style>
                    {{ form|crispy }}
                    {% csrf_token %}
                    <br>
                    <input class="btn btn-primary" type="submit" value="Отправить">
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}